# Generated by Django 3.0.6 on 2020-10-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('count', models.CharField(max_length=13)),
                ('radio', models.CharField(max_length=13)),
                ('date', models.DateField()),
            ],
        ),
    ]
